{% set name = "xzarrguard" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  noarch: python
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - xarray
    - zarr

test:
  imports:
    - xzarrguard
  commands:
    - xzarrguard --help
    - pytest -q -o addopts=''
  requires:
    - pytest
  source_files:
    - tests/

about:
  home: https://github.com/j-haacker/xzarrguard
  summary: Integrity checks and creation helpers for Zarr v3 stores
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/j-haacker/xzarrguard#readme
  dev_url: https://github.com/j-haacker/xzarrguard

extra:
  recipe-maintainers:
    - j-haacker
